/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.HibernateFestaDAO;
import dao.HibernateProdutoDAO;
import entidades.Festa;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import model.TableModelFesta;
import org.hibernate.exception.ConstraintViolationException;
import util.Impressao;

/**
 *
 * @author Julio
 */
public class ConsultaFestaView extends javax.swing.JDialog {

    private final HibernateProdutoDAO produtoDAO;
    private final HibernateFestaDAO hibernateFestaDAO;

    /**
     * Creates new form ConsultaProdutoView
     */
    public ConsultaFestaView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        festaDao = new HibernateFestaDAO();
        modelFesta = new TableModelFesta(festaDao);
        jTableFestas.setModel(modelFesta);
        produtoDAO = new HibernateProdutoDAO();
        hibernateFestaDAO = new HibernateFestaDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFestas = new javax.swing.JTable();
        jTextFieldFiltro = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonExtrato = new javax.swing.JButton();
        jButtonNovaVenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Festas");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jPanel1ComponentAdded(evt);
            }
        });

        jTableFestas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTableFestas.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTableFestas);
        jTableFestas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jTextFieldFiltro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jButtonNovo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/novo.png"))); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.setToolTipText("");
        jButtonNovo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonPesquisar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.setToolTipText("");
        jButtonPesquisar.setMaximumSize(new java.awt.Dimension(81, 25));
        jButtonPesquisar.setMinimumSize(new java.awt.Dimension(81, 25));
        jButtonPesquisar.setPreferredSize(new java.awt.Dimension(81, 25));
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setToolTipText("");
        jButtonEditar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonEditar.setMaximumSize(new java.awt.Dimension(81, 25));
        jButtonEditar.setMinimumSize(new java.awt.Dimension(81, 25));
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonRemover.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        jButtonRemover.setText("Remover");
        jButtonRemover.setToolTipText("");
        jButtonRemover.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonRemover.setMaximumSize(new java.awt.Dimension(81, 25));
        jButtonRemover.setMinimumSize(new java.awt.Dimension(81, 25));
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Filtro");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButtonExtrato.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonExtrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/impressora.png"))); // NOI18N
        jButtonExtrato.setText("Extrato    ");
        jButtonExtrato.setToolTipText("Imprime um extrato das vendas da festa selecionada");
        jButtonExtrato.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonExtrato.setMaximumSize(new java.awt.Dimension(81, 25));
        jButtonExtrato.setMinimumSize(new java.awt.Dimension(81, 25));
        jButtonExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExtratoActionPerformed(evt);
            }
        });

        jButtonNovaVenda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonNovaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nova-venda.png"))); // NOI18N
        jButtonNovaVenda.setText("Nova Venda");
        jButtonNovaVenda.setToolTipText("Inicia uma nova venda de produtos");
        jButtonNovaVenda.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonNovaVenda.setMaximumSize(new java.awt.Dimension(81, 25));
        jButtonNovaVenda.setMinimumSize(new java.awt.Dimension(81, 25));
        jButtonNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                            .addComponent(jTextFieldFiltro))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNovaVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtonExtrato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRemover, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jTextFieldFiltro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jButtonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonNovaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FestaView dialog = new FestaView(new javax.swing.JFrame(), true, modelFesta);
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jPanel1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jPanel1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentAdded

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        modelFesta.pesquisar(jTextFieldFiltro.getText());
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (jTableFestas.getSelectedRow() == -1) {
                    JOptionPane.showMessageDialog(null, "Selecione uma festa na linha da tabela para editá-la!");
                } else {
                    Festa encontado = modelFesta.getFesta(jTableFestas.getSelectedRow());
                    FestaView dialog = new FestaView(new javax.swing.JFrame(), true, modelFesta, encontado);
                    dialog.setLocationRelativeTo(null);
                    dialog.setVisible(true);
                }
            }
        });
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        if (jTableFestas.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma festa na linha da tabela para removê-lo!");
        } else {
            Festa encontado = modelFesta.getFesta(jTableFestas.getSelectedRow());
            int showConfirmDialog = JOptionPane.showConfirmDialog(this.getParent(), "Deseja realmente excluir essa festa ?", "Excluir Festa", JOptionPane.OK_CANCEL_OPTION);
            if (showConfirmDialog == 0) {
                try {
                    festaDao.remover(encontado.getId());
                    modelFesta.pesquisar("");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Está festa não pode ser removida porque possui venda(s) efetuadas!");
                }
            }
        }
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExtratoActionPerformed
        if (jTableFestas.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma festa na linha da tabela para imprimir o extrato !");
        } else {
            try {
                Impressao impressao = new Impressao();
                Festa encontado = modelFesta.getFesta(jTableFestas.getSelectedRow());
                impressao.imprimeExtrato(encontado, hibernateFestaDAO.buscarExtratoPorFesta(encontado));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao gerar extrato: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonExtratoActionPerformed

    private void jButtonNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaVendaActionPerformed
        if (jTableFestas.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma festa na linha da tabela para realizar uma nova venda !");
        } else if (!produtoDAO.hasProdutosAtivos()) {
            JOptionPane.showMessageDialog(null, "Cadastre produtos ativos antes de efetuar uma nova venda !");
        } else {
            Festa festa = modelFesta.getFesta(jTableFestas.getSelectedRow());
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    TelaDeVenda dialog = new TelaDeVenda(new javax.swing.JFrame(), true, festa, produtoDAO);
                    dialog.setLocationRelativeTo(null);
                    dialog.setVisible(true);
                }
            });
        }
    }//GEN-LAST:event_jButtonNovaVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaFestaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaFestaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaFestaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaFestaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultaFestaView dialog = new ConsultaFestaView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private HibernateFestaDAO festaDao;
    private final TableModelFesta modelFesta;
    private JScrollPane barraRolagem;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExtrato;
    private javax.swing.JButton jButtonNovaVenda;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFestas;
    private javax.swing.JTextField jTextFieldFiltro;
    // End of variables declaration//GEN-END:variables
}
